import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";

const openSansMedium = localFont({
  src: "./fonts/OpenSans-Medium.ttf",
  variable: "--font-open-sans-medium",
  weight: "500",
});

const openSansSemiBold = localFont({
  src: "./fonts/OpenSans-SemiBold.ttf",
  variable: "--font-open-sans-semi-bold",
  weight: "600",
});

export const metadata: Metadata = {
  title: "Drąsi Virtuvė",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" href="/favicon.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body
        className={`${openSansMedium.variable} ${openSansSemiBold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
